locals {
  # if no domain was supplied, fall back to <ip>.nip.io so Caddy can still
  # obtain a real LE cert without us having to register anything
  effective_domain = var.domain != "" ? var.domain : "${google_compute_address.vm.address}.nip.io"

  # tag every resource so the shared `formulai` project stays tidy
  labels = {
    component = "tasks-stack"
    managed   = "terraform"
    repo      = replace(var.github_repo, "/", "-")
  }
}

# ---------------------------------------------------------------------------
# strong postgres password generated by terraform and injected via metadata.
# stored only in tf state (which lives in a private GCS bucket) and in the
# VM's /opt/tasks/.env file (root, 0600).
# ---------------------------------------------------------------------------
resource "random_password" "postgres" {
  length      = 32
  special     = false # avoid url-escaping headaches in DATABASE_URL
  min_lower   = 4
  min_upper   = 4
  min_numeric = 4
}

# ---------------------------------------------------------------------------
# the VM's own service account. minimal -- only what the Ops Agent needs.
# explicitly NOT given deploy/admin power, so a VM compromise can't
# manipulate the project.
# ---------------------------------------------------------------------------
resource "google_service_account" "vm" {
  account_id   = "${var.name_prefix}-vm-runtime"
  display_name = "Runtime SA for the tasks VM"
}

resource "google_project_iam_member" "vm_logging" {
  project = var.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.vm.email}"
}

resource "google_project_iam_member" "vm_metrics" {
  project = var.project_id
  role    = "roles/monitoring.metricWriter"
  member  = "serviceAccount:${google_service_account.vm.email}"
}

# ---------------------------------------------------------------------------
# static external IP. survives stop/start, so DNS / Caddy state aren't broken
# by a reboot.
# ---------------------------------------------------------------------------
resource "google_compute_address" "vm" {
  name         = "${var.name_prefix}-vm-ip"
  region       = var.region
  address_type = "EXTERNAL"
  network_tier = "STANDARD" # cheaper than PREMIUM, fine for one VM
}

# ---------------------------------------------------------------------------
# firewall: defence in depth alongside UFW on the host.
# 22 only from var.allowed_ssh_cidr, 80/443 from the world.
# we tag the VM so these rules apply only to it, not other VMs in formulai.
# ---------------------------------------------------------------------------
resource "google_compute_firewall" "ssh" {
  name    = "${var.name_prefix}-ssh"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = [var.allowed_ssh_cidr]
  target_tags   = ["${var.name_prefix}-vm"]
}

resource "google_compute_firewall" "web" {
  name    = "${var.name_prefix}-web"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["80", "443"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["${var.name_prefix}-vm"]
}

# ---------------------------------------------------------------------------
# the VM itself. e2-small / debian-12. startup script handles all of:
#   - install docker + compose plugin
#   - create deploy user, install ssh keys
#   - write /opt/tasks/.env with generated postgres password
#   - configure ufw / fail2ban / unattended-upgrades
# the startup script is idempotent so reboots don't re-trigger anything.
# ---------------------------------------------------------------------------
resource "google_compute_instance" "vm" {
  name         = "${var.name_prefix}-vm"
  machine_type = var.machine_type
  zone         = var.zone
  tags         = ["${var.name_prefix}-vm"]
  labels       = local.labels

  boot_disk {
    initialize_params {
      image = var.boot_disk_image
      size  = var.boot_disk_size_gb
      type  = "pd-balanced"
    }
  }

  network_interface {
    network = "default"
    access_config {
      nat_ip       = google_compute_address.vm.address
      network_tier = "STANDARD"
    }
  }

  service_account {
    email = google_service_account.vm.email
    scopes = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring.write",
    ]
  }

  metadata = {
    # GCP's metadata server merges these; the OS Login flag is off so
    # ssh-keys metadata works as expected.
    enable-oslogin = "FALSE"
    ssh-keys = join("\n", [
      for k in var.ssh_pub_keys : "${var.ssh_user}:${k}"
    ])

    # values consumed by the startup script
    deploy-user       = var.ssh_user
    domain            = local.effective_domain
    acme-email        = var.acme_email
    image-owner       = var.image_owner
    postgres-user     = "tasks"
    postgres-db       = "tasks"
    postgres-password = random_password.postgres.result
  }

  metadata_startup_script = templatefile("${path.module}/cloud-init.sh.tftpl", {
    deploy_user       = var.ssh_user
    domain            = local.effective_domain
    acme_email        = var.acme_email
    image_owner       = var.image_owner
    postgres_password = random_password.postgres.result
  })

  allow_stopping_for_update = true

  lifecycle {
    # the postgres password is in metadata; ignore drift on it so a
    # password rotation doesn't recreate the VM (would wipe the disk).
    # rotate by SSH + rewriting /opt/tasks/.env instead.
    ignore_changes = [metadata["postgres-password"]]
  }
}
